import re
f = open("Exercise.txt","r")
s = f.read()
phonenumber = re.findall("[0-9]+-[0-9]+-[0-9]+",s)
print(phonenumber)
email = re.findall("[a-z]+@[a-z]+.[a-z]+", s)
print(email)
name= re.findall("[A-Z][a-z]+ [A-Z][a-z]+\n",s)
print(name)
zipcode = re.findall(" [0-9]+\n",s)
print(zipcode)
doornumber = re.findall("\n[0-9]+ ",s)
print(doornumber)
area = re.findall(" [A-Za-z]+ [A-Za-z]+ ",s)
print(area)
street = re.findall(" [0-9A-Za-z]+ St.",s)
print(street)